server:
  port: ${SERVER_PORT:8443}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: ${GATEWAY_NAME:gateway-web}
  datasource:
    url: jdbc:mysql://localhost:3306/sc_admin?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    #password: ${REDIS_PASSWORD:}
  #jwt密码
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    gateway:
      default-filters:
      - name: Retry
        args:
          retries: 1
          statuses: BAD_GATEWAY
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      - name: RequestRateLimiter
        args:
          redis-rate-limiter.replenishRate: 2  #流速 每秒
          redis-rate-limiter.burstCapacity: 10   #令牌桶的容积
          rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
          key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean

#网关白名单，无需要签权url
gate:
  authentication:
    enable: true
    ignore:
      startWith: /oauth,/open
    resource:
      enable: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.springcloud.manager
  local:
    # 默认2小时本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 3600000
      expireAfterAccessInMillis: 1800000
    # 長時本地緩存，主要用于要求时效一般
    longTime:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 300000
      expireAfterAccessInMillis: 180000
    # 短時本地緩存，主要用于要求时效较高的配置
    shortTime:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 60000
      expireAfterAccessInMillis: 40000
  remote:
    # 默认2小时的远程缓存
    default:
      type: redis
      expireAfterWriteInMillis: 43200000
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
    # 长时远程緩存，主要用于要求时效要求一般的集中式缓存
    longTime:
      type: redis
      expireAfterWriteInMillis: 7200000
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
    # 短時远程緩存，主要用于要求时效较高的集中式缓存
    shortTime:
      type: redis
      expireAfterWriteInMillis: 300000
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    com.springboot.cloud.gateway: debug
    com.jalja.org.spring: debug
  path: logs/
  file:
    max-size: 1GB
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000