logging:
  level:
    cn.springcloud.book.feign.service.HelloFeignService: debug
feign:
  httpclient:
    enable: false
  okhttp:
    enable: true019
#  compression:
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
#    response:
#      enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sc_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
